server:
  port: 8090
spring:
  application:
    name: order-service
  profiles:
    active: local
  # 开启 bus 追踪，用于热刷新
  cloud:
    bus:
      trace:
        enabled: true

feign:
  # 启动 okhttp
  okhttp:
    enabled: true
  # gzip
  compression:
    request:
      enabled: true
      # 配置压缩支持的 MIME type
      mime-types: application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      enabled: true
  # 启动 熔断器
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

# 设置饥饿加载 避免第一次加载特别慢
ribbon:
  eager-load:
    enabled: true
    clients: patient-service