spring:
  profiles:
    active: local

  application:
    name: payment-service

  messages:
    basename: i18n/messages
    encoding: UTF-8
  aop:
    auto: true
    proxy-target-class: true
  resources:
    chain:
      compressed: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 30MB
      location: ${user.dir}