server:
  port: 7890

spring:
  profiles: local

eureka:
  client:
    eureka-server-connect-timeout-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/


jwt:
  # 密钥
  secret: xfk!@#$%^&*()xfk!@#$%^&*()xfk!@#$%^&*()
  # 七天
  expiration: 604800
  # 续约30天
  renew-expiration: 2592000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    '*': debug
