spring:
  profiles:
    active: local

  application:
    name: gateway-server

  messages:
    basename: i18n/messages
    encoding: UTF-8
  aop:
    auto: true
    proxy-target-class: true
  resources:
    chain:
      compressed: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 30MB
      location: ${user.dir}

feign:
  # 启动 okhttp
  okhttp:
    enabled: true
  # gzip
  compression:
    request:
      enabled: true
      # 配置压缩支持的 MIME type
      mime-types: application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      enabled: true
  # 启动 熔断器
  hystrix:
    enabled: true