spring:
  profiles: docker

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    eureka-server-connect-timeout-seconds: 30
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka/


jwt:
  # 密钥
  secret: xfk!@#$%^&*()xfk!@#$%^&*()xfk!@#$%^&*()
  # 七天
  expiration: 604800
  # 续约30天
  renew-expiration: 2592000

logging:
  level:
    org.springframework.cloud.gateway: debug
