server:
  port: 9090

spring:
  application:
    name: git-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lynings/spring-config-demo.git
#          username:
#          password:
          search-paths: CONFIG
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

