spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lynings/spring-config-demo.git
          username: 645464704@qq.com
          password: qaz748596123.
          search-paths: CONFIG
          delete-untracked-branches: true
          timeout: 30
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

