spring:
  application:
    name: apm-admin

  resources:
    chain:
      compressed: true

  security:
    user:
      name: xfk
      password: xfk123

  boot:
    admin:
      discovery:
        ignored-services: apm-admin

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8010}/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS