spring:
  application:
    name: registry-server
  profiles:
    active: local

  messages:
    basename: i18n/messages
    encoding: UTF-8
  aop:
    auto: true
    proxy-target-class: true
  resources:
    chain:
      compressed: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 30MB
      location: ${user.dir}

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,*/*

