spring:
  application:
    name: registry-server
  profiles:
    active: local

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,*/*

