apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: ddd-microservices
  labels:
    service: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - name: http
      port: 7890
      targetPort: 8080
  clusterIP: 10.96.0.4
  externalIPs:
    - {{VM_IP}}
