apiVersion: v1
kind: Service
metadata:
  name: registry-server
  namespace: ddd-microservices
  labels:
    service: registry-server
spec:
  selector:
    app: registry-server
  ports:
    - name: http
      port: 8010
      targetPort: 8080
  clusterIP: 10.96.0.3
  externalIPs:
    - ${MY_HOST}
