apiVersion: v1
kind: Service
metadata:
  name: order-server
  namespace: ddd-microservices
  labels:
    service: order-server
spec:
  selector:
    app: order-server
    peer: "1"
  ports:
    - name: http
      port: 8761
      targetPort: 8080
  clusterIP: 10.96.0.3
  externalIPs:
    - {{VM_IP}}
