apiVersion: v1
kind: Service
metadata:
  name: patient-server
  namespace: ddd-microservices
  labels:
    service: patient-server
spec:
  selector:
    app: patient-server
  ports:
    - name: http
      port: 8001
      targetPort: 8080
  clusterIP: 10.96.0.6
  externalIPs:
    - {{VM_IP}}
