server:
  port: 1212

spring:
  profiles: local

  # rabbitmq 配置
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        place-order:
          destination: orders-exchange
          group: orders-queue


management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: ALWAYS