server:
  port: 8090
spring:
  profiles: local

  # rabbitmq 配置
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

  # spring data jpa configure
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    pers.lyning.springcloud.ordercontext.gateways.acl.user.UserClient: debug
